/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Options passed from JavaScript/TypeScript for encoding */
export interface JsEncodeOptions {
  ownerIdHashHex: string
  kekIdHex: string
  cipherSuite?: number
  flags?: number
  imageUuidHex?: string
}
/** Metadata inspected from a SIF header */
export interface JsSifHeader {
  version: number
  cipherSuite: number
  flags: number
  imageUuidHex: string
  ownerIdHashHex: string
  kekIdHex: string
  payloadLength: number
}
/** Result returned from decoding */
export interface JsDecodedResult {
  header: JsSifHeader
  plaintext: Buffer
}
/** Key pair generated for Ed25519 signing */
export interface JsKeyPair {
  privateKeyHex: string
  publicKeyHex: string
}
/** Generate a new Ed25519 keypair in hex format */
export declare function generateKeypair(): JsKeyPair
/** Inspects a SIF container header without requiring KEK or decryption */
export declare function inspectSif(sifBuffer: Buffer): JsSifHeader
/** Encodes raw image bytes into a SIF container buffer (Runs asynchronously in worker pool) */
export declare function encodeSif(plaintext: Buffer, kek: Buffer, privateKeyHex: string, options: JsEncodeOptions): Promise<Buffer>
/** Decodes and verifies a SIF container buffer (Runs asynchronously in worker pool) */
export declare function decodeSif(sifBuffer: Buffer, kek: Buffer, publicKeyHex: string): Promise<JsDecodedResult>
